language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - docker
  - mysql

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - chmod +x mvnw
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -proot
  - sudo service mysql restart
  - sudo mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS test_tmp;'
  - sudo mysql -u root -proot -e 'use test_tmp; CREATE TABLE tb_user (id int(11) NOT NULL AUTO_INCREMENT, user_name varchar(50) NOT NULL, password varchar(50) NOT NULL, phone varchar(20) NOT NULL, create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "aw4VF4rhH3vHmLAPevlqYumii1t4RLA6hs0HXmHXQwhjfsnWQf42j1wJrtf3perM+UzWPemiUB7JJothJftXqNH3zxsVpFr86dEV1bHYjF6nB/MVvjyxgvh/ETmZ97WvetkZsGC/DIy3as76kQ44Eg9lCDeH+ytdsxpux5vZvt7GwYHjPa1yzfc754fGhIj+7vmEikhmbWD8JNicZkBmqp7RtsvDtVTfdiGOR+Qc4a6oCBpPE5g4+khbRqGAsdIzaQeH+HksDJCF1hIe00AQMky7vLgQF83mnpwCuCsQzphzM1sf8nYFlF1CaGlUYPk54gtB8Jq/s0s96UveBNryMMgw5K6X0fZPtDZDq8E4dFbM9uTGrbNWi3MOXoIpXNWhG2yBborbbADmth6TW+9sGFAncHed/IAao/9pAVcEawoe966IWe6YFUqyvLrTNrTTsmrGmIyBDz5VScrNVbO1QT/kr6NtlevTrrADSq6VnZVNXwgdX/HhOIv9dza/4jGZvTW2nPzjJHWyVGd5C7+I+2//BJ0941MlpS7gFPjIBBKTOBBnG82ZuuT+H9eAcKaMJfJz99kYQlh2FxA5UBpbwiOMS0ZXZ28yy7UWmf8G+UWXAEKhm6cbWck0m5xYWjnyJ0dDTfl1XNsWikDmkJXcE3QrDV15P3TRpve3B6yaU8s="